<a href="https://colab.research.google.com/github/DrJHSIM/PyTorch_Practice/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

## Tensor 초기화

### 데이터로 부터 바로 생성

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

### Numpy에서 부터 생성

In [3]:
np_array = np.array(data)
t_data = torch.from_numpy(np_array)

In [4]:
print(t_data)

tensor([[1, 2],
        [3, 4]])


### 다른 텐서로부터 생성

인수로 받는 tensor의 특성을 받음 (shape, dtype, device).

In [7]:
x_ones = torch.ones_like(t_data)
print(f"Ones Tensor : {x_ones}")
x_rand = torch.rand_like(t_data, dtype = torch.float)
print(f"Zeros Tensor : {x_rand}")

Ones Tensor : tensor([[1, 1],
        [1, 1]])
Zeros Tensor : tensor([[0.0117, 0.0425],
        [0.4654, 0.2946]])


### shape으로 생성

In [8]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor}")
print(f"Ones Tensor : \n {ones_tensor}")
print(f"Zeros Tensor : \n {zeros_tensor}")

Random Tensor : 
 tensor([[0.9120, 0.5602, 0.6134],
        [0.7783, 0.1489, 0.5708]])
Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor 연산들(operations)

tensor에는 100개가 넘는 연산자들이 있음. \
https://pytorch.org/docs/stable/torch.html


### tensor를 GPU로 보내고 싶을 경우.

In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

### tensor의 indexing과 slicing (NumPy같이 할 수 있음)

In [9]:
tensor = torch.ones(4, 4)
print(f"row : {tensor[0]}")
print(f"column : {tensor[:, 0]}")
print(f"Last column : {tensor[... , -1]}")
tensor[:, 1] = 0
print(tensor)

row : tensor([1., 1., 1., 1.])
column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### tensor들을 연결하기(joining)

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### 산술(Arithmetic) 연산들(operations)

In [11]:
# 행렬곱
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# 원소별곱(element-wise product)
y3 = tensor*tensor
y4 = tensor.mul(tensor)

### 단일 원소 텐서(Single-element tensors)

단일 원소 텐서를 얻기 위해서는 텐서를 .item()을 사용하여 파이썬의 수치적인 값으로 바꾸어야 함.

In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### in-place 연산들

결과를 피연산자(operand)에 저장하는 것을 in-place라 함. _ 접미사(suffix)로 표기함. \
(메모리를 절약할 수 있지만, derivative을 계산할 경우 문제가 되어 잘 쓰지 않음)

In [14]:
print(f"{tensor}\n")
tensor.add_(5)
print(f"{tensor}\n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])



### NumPy에서 Tensor로
CPU에서 tensors는 NumPy arrays와 기본적으로 메모리 위치를 공유해서 하나가 바뀌면 다른 것도 바뀜.

#### Tensor에서 Numpy로...

In [20]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


tensor의 값을 바꾸면 NumPy의 array에도 반영됨.

In [21]:
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


#### NumPy에서 Tensor로..

In [18]:
np_array = np.ones(5)
t_array = torch.from_numpy(np_array)
print(f"numpy : {np_array} \ntensor : {t_array}")

numpy : [1. 1. 1. 1. 1.] 
tensor : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


NumPy의 array의 값을 바꾸면 tensor의 값도 바뀜.

In [19]:
np.add(np_array, 1, out = np_array)
print(f"np_array : {np_array}")
print(f"t_array : {t_array}")

np_array : [2. 2. 2. 2. 2.]
t_array : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
